import React from "react";
import "./Style.css";
import myimg from "./img/first.png";

const Home = () => {
  return (
    <div>
      <section className="section-hero">
        <div className="hero">
          <div className="hero-text-box">
            <h1 className="heading-primary">
              Analyze any text with a click of a button
            </h1>
            <p className="hero-description">
              Text-o-matic can condense articles, papers, or documents down to
              the key points instantly. Our AI uses natural language processing
              to locate critical information while maintaining the original
              context.
            </p>

            <a href="#" className="btn btn--outline">
              Learn more ↓
            </a>
            <div className="delivered-meals">
              <div className="delivered-imgs">
                {/* <img src="img/customers/customer-1.jpg" alt="Customer photo" />
                <img src="img/customers/customer-2.jpg" alt="Customer photo" />
                <img src="img/customers/customer-3.jpg" alt="Customer photo" />
                <img src="img/customers/customer-4.jpg" alt="Customer photo" />
                <img src="img/customers/customer-5.jpg" alt="Customer photo" />
                <img src="img/customers/customer-6.jpg" alt="Customer photo" /> */}
              </div>
              <p className="delivered-text">
                {/* <span>250,000+</span> xyz xyz xyz xyz xyz */}
              </p>
            </div>
          </div>
          <div className="hero-img-box">
            <img
              src={myimg}
              className="hero-img"
              alt="intelligent text analyzer"
            />
          </div>
          <div id="features" className="col-row row">
            <h1>Features</h1>
          </div>
          <div className="col-md-8 d-flex align-items-center">
            <ul className="list-unstyled ui-steps">
              <li className="media" id={1}>
                <div id="icon-1" className="circle-icon mr-4">
                  1
                </div>
                <div className="media-body">
                  <h1>Summary Generation</h1>
                  <p>
                    The better version of your information will be generated by
                    extracting the most important parts of it.
                  </p>
                </div>
              </li>
              <li className="media" id={2}>
                <div id="icon-2" className="circle-icon mr-4">
                  2
                </div>
                <div className="media-body">
                  <h1>Sentiment analyzer</h1>
                  <p>Get .......</p>
                </div>
              </li>

              <li className="media" id={6}>
                <div id="icon-6" className="circle-icon mr-4">
                  3
                </div>
                <div className="media-body">
                  <h1>Save Your Results</h1>
                  <p>Download, save or share your summary for free.</p>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Home;
