import React from "react";
import "./Style.css";
import myimg from "./img/logonew.png";

const Home = () => {
  return (
    <div>
      <section className="section-hero">
        <div className="hero">
          <div className="hero-text-box">
            <h1 className="heading-primary">
              Analyze any text with a click of a button
            </h1>
            <p className="hero-description">
              Text-o-matic can condense articles, papers, or documents down to
              the key points instantly. Our AI uses natural language processing
              to locate critical information while maintaining the original
              context.
            </p>

            <a href="#" className="btn btn--outline">
              Learn more ↓
            </a>
          </div>
          <div className="hero-img-box">
            <img
              src={myimg}
              className="hero-img img-fluid animate__animated animate__pulse"
              alt="intelligent text analyzer"
            />
          </div>
          {/* ////////////////////////////////////////////////// */}

          {/* <div id="features" className="col-row row">
            <h1>Features</h1>
          </div>
          <div className="col-md-8 d-flex align-items-center">
            <ul className="list-unstyled ui-steps">
              <li className="media" id={1}>
                <div id="icon-1" className="circle-icon mr-4">
                  1
                </div>
                <div className="media-body">
                  <h1>Summary Generation</h1>
                  <p>
                    The better version of your information will be generated by
                    extracting the most important parts of it.
                  </p>
                </div>
              </li>
              <li className="media" id={2}>
                <div id="icon-2" className="circle-icon mr-4">
                  2
                </div>
                <div className="media-body">
                  <h1>Sentiment analyzer</h1>
                  <p>Get .......</p>
                </div>
              </li>

              <li className="media" id={6}>
                <div id="icon-6" className="circle-icon mr-4">
                  3
                </div>
                <div className="media-body">
                  <h1>Save Your Results</h1>
                  <p>Download, save or share your summary for free.</p>
                </div>
              </li>
            </ul> */}
          {/* </div> */}
        </div>
      </section>

      {/* ////////////////////////////////////////////////////////////////////// */}

      <section>
        <div style={{ background: "#dff1ee" }}>
          <div className="container">
            <br />
            <p className="display-6  text-center "> Get started in minutes</p>
            <p className="display-4 text-center ">
              3 simple & easy step to launch.
            </p>
            <br />
            <br />
            <div className="row">
              <div className="col-sm-4">
                <div
                  className="card w-80 animate__animated animate__slideInUp "
                  style={{ background: "#dff1ee" }}
                >
                  <div className="card-body" style={{ transition: "1sec" }}>
                    <img
                      src="https://www.sammurize.com/images/assets/ils_15.svg"
                      alt=""
                      className="img-fluid  card-img-top "
                    />
                    <p>Join Our Platform</p>
                    <p className=" fw-bold">
                      It only takes a minute. <br /> Set up is smooth and simple
                    </p>
                  </div>
                </div>
              </div>
              <div className="col-sm-4">
                <div
                  className="card w-80 animate__animated animate__slideInUp"
                  style={{ background: "#dff1ee" }}
                >
                  <div className="card-body">
                    <img
                      src="https://www.sammurize.com/images/assets/ils_16.svg"
                      alt=""
                      className="img-fluid  card-img-top"
                    />
                    <p>Create new research</p>
                    <p className=" fw-bold">
                      Create a new research and start gathering documents as pdf
                      files or public URL article links
                    </p>
                  </div>
                </div>
              </div>
              <div className="col-sm-4">
                <div
                  className="card w-80 animate__animated animate__slideInUp"
                  style={{ background: "#dff1ee" }}
                >
                  <div className="card-body">
                    <img
                      src="https://www.sammurize.com/images/assets/ils_07.svg"
                      alt=" "
                      width="100"
                      className="img-fluid card-img-top"
                    />
                    <p>Start summarizing text</p>
                    <p className=" fw-bold">
                      Get detailed keywords and <br /> summarize main points{" "}
                      <br /> for each document
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* /////////////////////// */}

      <section>
        <div id="features" className="col-row row" style={{ display: "flex", justifyContent:"center", alignItems:"center" }}>
          <h1>Features</h1>
        </div>
        <div className="col-md-8 d-flex align-items-center">
          <ul className="list-unstyled ui-steps">
            <li className="media" id={1}>
              <div id="icon-1" className="circle-icon mr-4">
                1
              </div>
              <div className="media-body">
                <h1>Summary Generation</h1>
                <p>
                  The better version of your information will be generated by
                  extracting the most important parts of it.
                </p>
              </div>
            </li>
            <li className="media" id={2}>
              <div id="icon-2" className="circle-icon mr-4">
                2
              </div>
              <div className="media-body">
                <h1>Sentiment analyzer</h1>
                <p>Get .......</p>
              </div>
            </li>

            <li className="media" id={6}>
              <div id="icon-6" className="circle-icon mr-4">
                3
              </div>
              <div className="media-body">
                <h1>Save Your Results</h1>
                <p>Download, save or share your summary for free.</p>
              </div>
            </li>
          </ul>
        </div>
      </section>
    </div>
  );
};

export default Home;
